{ id: '18541570',
  displayName: 'Juan D. Acosta',
  username: 'juandaco',
  profileUrl: 'https://github.com/juandaco',
  emails: [ { value: 'juandacorias@gmail.com' } ],
  provider: 'github',
  _raw: '{"login":"juandaco","id":18541570,"avatar_url":"https://avatars0.githubusercontent.com/u/18541570?v=3","gravatar_id":"","url":"https://api.github.com/users/juandaco","html_url":"https://github.com/juandaco","followers_url":"https://api.github.com/users/juandaco/followers","following_url":"https://api.github.com/users/juandaco/following{/other_user}","gists_url":"https://api.github.com/users/juandaco/gists{/gist_id}","starred_url":"https://api.github.com/users/juandaco/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/juandaco/subscriptions","organizations_url":"https://api.github.com/users/juandaco/orgs","repos_url":"https://api.github.com/users/juandaco/repos","events_url":"https://api.github.com/users/juandaco/events{/privacy}","received_events_url":"https://api.github.com/users/juandaco/received_events","type":"User","site_admin":false,"name":"Juan D. Acosta","company":null,"blog":null,"location":"Pereira Colombia","email":"juandacorias@gmail.com","hireable":null,"bio":"Musician and Web Developer","public_repos":10,"public_gists":0,"followers":0,"following":1,"created_at":"2016-04-19T00:12:17Z","updated_at":"2017-03-21T16:47:16Z"}',
  _json:
   { login: 'juandaco',
     id: 18541570,
     avatar_url: 'https://avatars0.githubusercontent.com/u/18541570?v=3',
     gravatar_id: '',
     url: 'https://api.github.com/users/juandaco',
     html_url: 'https://github.com/juandaco',
     followers_url: 'https://api.github.com/users/juandaco/followers',
     following_url: 'https://api.github.com/users/juandaco/following{/other_user}',
     gists_url: 'https://api.github.com/users/juandaco/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/juandaco/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/juandaco/subscriptions',
     organizations_url: 'https://api.github.com/users/juandaco/orgs',
     repos_url: 'https://api.github.com/users/juandaco/repos',
     events_url: 'https://api.github.com/users/juandaco/events{/privacy}',
     received_events_url: 'https://api.github.com/users/juandaco/received_events',
     type: 'User',
     site_admin: false,
     name: 'Juan D. Acosta',
     company: null,
     blog: null,
     location: 'Pereira Colombia',
     email: 'juandacorias@gmail.com',
     hireable: null,
     bio: 'Musician and Web Developer',
     public_repos: 10,
     public_gists: 0,
     followers: 0,
     following: 1,
     created_at: '2016-04-19T00:12:17Z',
     updated_at: '2017-03-21T16:47:16Z' } }