{ id: '893443964',
   username: 'juandacorias',
   displayName: 'Juan D. Acosta',
   photos: [ { value: 'https://pbs.twimg.com/profile_images/808442069299687424/-3aWphw4_normal.jpg' } ],
   provider: 'twitter',
   _raw: '{"id":893443964,"id_str":"893443964","name":"Juan D. Acosta","screen_name":"juandacorias","location":"","description":"","url":null,"entities":{"description":{"urls":[]}},"protected":false,"followers_count":4,"friends_count":36,"listed_count":0,"created_at":"Sat Oct 20 15:16:33 +0000 2012","favourites_count":0,"utc_offset":null,"time_zone":null,"geo_enabled":false,"verified":false,"statuses_count":1,"lang":"en","status":{"created_at":"Tue Dec 13 10:55:54 +0000 2016","id":808626494058676225,"id_str":"808626494058676225","text":"Generated with Processing, uploaded with node.js https:\\/\\/t.co\\/jLec7ct1qX","truncated":false,"entities":{"hashtags":[],"symbols":[],"user_mentions":[],"urls":[],"media":[{"id":808626490082467840,"id_str":"808626490082467840","indices":[49,72],"media_url":"http:\\/\\/pbs.twimg.com\\/media\\/CzjRgilWIAAHFaw.jpg","media_url_https":"https:\\/\\/pbs.twimg.com\\/media\\/CzjRgilWIAAHFaw.jpg","url":"https:\\/\\/t.co\\/jLec7ct1qX","display_url":"pic.twitter.com\\/jLec7ct1qX","expanded_url":"https:\\/\\/twitter.com\\/juandacorias\\/status\\/808626494058676225\\/photo\\/1","type":"photo","sizes":{"large":{"w":640,"h":360,"resize":"fit"},"small":{"w":640,"h":360,"resize":"fit"},"thumb":{"w":150,"h":150,"resize":"crop"},"medium":{"w":640,"h":360,"resize":"fit"}}}]},"extended_entities":{"media":[{"id":808626490082467840,"id_str":"808626490082467840","indices":[49,72],"media_url":"http:\\/\\/pbs.twimg.com\\/media\\/CzjRgilWIAAHFaw.jpg","media_url_https":"https:\\/\\/pbs.twimg.com\\/media\\/CzjRgilWIAAHFaw.jpg","url":"https:\\/\\/t.co\\/jLec7ct1qX","display_url":"pic.twitter.com\\/jLec7ct1qX","expanded_url":"https:\\/\\/twitter.com\\/juandacorias\\/status\\/808626494058676225\\/photo\\/1","type":"photo","sizes":{"large":{"w":640,"h":360,"resize":"fit"},"small":{"w":640,"h":360,"resize":"fit"},"thumb":{"w":150,"h":150,"resize":"crop"},"medium":{"w":640,"h":360,"resize":"fit"}}}]},"source":"\\u003ca href=\\"http:\\/\\/shiffman.net\\" rel=\\"nofollow\\"\\u003eNodeJS TwitterBot\\u003c\\/a\\u003e","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":0,"favorite_count":0,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"en"},"contributors_enabled":false,"is_translator":false,"is_translation_enabled":false,"profile_background_color":"C0DEED","profile_background_image_url":"http:\\/\\/abs.twimg.com\\/images\\/themes\\/theme1\\/bg.png","profile_background_image_url_https":"https:\\/\\/abs.twimg.com\\/images\\/themes\\/theme1\\/bg.png","profile_background_tile":false,"profile_image_url":"http:\\/\\/pbs.twimg.com\\/profile_images\\/808442069299687424\\/-3aWphw4_normal.jpg","profile_image_url_https":"https:\\/\\/pbs.twimg.com\\/profile_images\\/808442069299687424\\/-3aWphw4_normal.jpg","profile_link_color":"1DA1F2","profile_sidebar_border_color":"C0DEED","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"has_extended_profile":false,"default_profile":true,"default_profile_image":false,"following":false,"follow_request_sent":false,"notifications":false,"translator_type":"regular"}',
   _json:
    { id: 893443964,
      id_str: '893443964',
      name: 'Juan D. Acosta',
      screen_name: 'juandacorias',
      location: '',
      description: '',
      url: null,
      entities: { description: [Object] },
      protected: false,
      followers_count: 4,
      friends_count: 36,
      listed_count: 0,
      created_at: 'Sat Oct 20 15:16:33 +0000 2012',
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 1,
      lang: 'en',
      status:
       { created_at: 'Tue Dec 13 10:55:54 +0000 2016',
         id: 808626494058676200,
         id_str: '808626494058676225',
         text: 'Generated with Processing, uploaded with node.js https://t.co/jLec7ct1qX',
         truncated: false,
         entities: [Object],
         extended_entities: [Object],
         source: '<a href="http://shiffman.net" rel="nofollow">NodeJS TwitterBot</a>',
         in_reply_to_status_id: null,
         in_reply_to_status_id_str: null,
         in_reply_to_user_id: null,
         in_reply_to_user_id_str: null,
         in_reply_to_screen_name: null,
         geo: null,
         coordinates: null,
         place: null,
         contributors: null,
         is_quote_status: false,
         retweet_count: 0,
         favorite_count: 0,
         favorited: false,
         retweeted: false,
         possibly_sensitive: false,
         lang: 'en' },
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: 'C0DEED',
      profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/808442069299687424/-3aWphw4_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/808442069299687424/-3aWphw4_normal.jpg',
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      has_extended_profile: false,
      default_profile: true,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'regular' },
      _accessLevel: 'read' }